substitutions:
  name: watermeter
  vdate: "v25.5.1"

esphome:
  name: ${name}
  friendly_name: ${name}
  platformio_options:
    board_build.flash_mode: dio
     
esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf #redundant to core .yml, but left in for clarity
    sdkconfig_options: 
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Also enable this on any derivative boards (S2, C3 etc) but not the original ESP32.
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      # Extend the watchdog timeout, so the device reboots if the device appears locked up for over 10 seconds.
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

# Enable logging
logger:
#  level: INFO
# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key12

ota:
  - platform: esphome
    password: ""

packages:
  wifi: !include common/wifi.yaml 
  remote_package_files:
    url: https://github.com/mvroosmalen1970/watermeter.git
    files: [components/main.yaml]
    ref: main
    refresh: 0d

# bluetooth_proxy:
    
