# Enable Home Assistant API
# Set pulse counter total from home assistant using this service call:
api:
  services:
    - service: set_pulse_total
      variables:
        new_pulse_total: int
      then:
        - pulse_counter.set_total_pulses:
            id: water_consumption
            value: !lambda 'return new_pulse_total;'

# Water flow meter using LJ18A3-8-Z/BX sensor (5V, 8mm distance)
# Generic sensor config:
#   https://esphome.io/components/sensor/index.html#config-sensor
# Pulse counter config:
#   https://esphome.io/components/sensor/pulse_counter.html
# Example project:
#   https://www.pieterbrinkman.com/2022/02/02/build-a-cheap-water-usage-sensor-using-esphome-home-assistant-and-a-proximity-sensor/
#
sensor:
  # Uptime in seconds
  - platform: uptime
    name: "uptime"
    id: uptime_seconds
    update_interval: 10s
  # Pulse COUNTER reports water usage in absolute liters
  - platform: pulse_counter
    pin:
      number: GPIO4
      inverted: true    # Active LOW input, does not really matter since we're counting pulses
      mode:
        input: true
    id: water_consumption
    name: "Water consumption"
    unit_of_measurement: 'liter'
    device_class: water
    state_class: total_increasing
    #last_reset: None
    #
    icon: "mdi:water"
    update_interval: 6s
    #
    total:
      id: water_consumption_total
      name: "Water consumption total"
      unit_of_measurement: "m³"
      icon: "mdi:water"
      #
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      #last_reset: None
      filters:
        - multiply: 0.001
