#vijversensor
esphome:
  on_boot:
    - priority: -10
      then: 
        - lambda: |- 
            id(versie).publish_state("v25.6.3");

text_sensor:
  - platform: template
    name: "watersensor - versie"
    id: versie
    icon: 'mdi:alpha-v-circle-outline' 
  - platform: wifi_info
    ip_address:
      name: "watermeter IP-adres"
      id: ip_adres
      icon: mdi:ip-network
    ssid:
      name: "watermeter Netwerk"
      id: netwerk
      icon: mdi:access-point-network
    mac_address:
      name: "watermeter Mac-adres"
      id: mac_adres
      icon: mdi:folder-key-network-outline

#DS18B20
one_wire:
  - platform: gpio
    pin: GPIO13
    id: x1
#  restart button  #
button:  
  - platform: restart
    name: "Restart device"
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  # Uptime in seconds
  - platform: uptime
    name: "uptime"
    id: uptime_seconds
    update_interval: 10s
  - platform: dallas_temp
    one_wire_id: x1     
    address: 0x470417b2ed80ff28
    name: "Vijver temperature"
    update_interval: 3s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
          send_first_at: 1    
  - platform: ultrasonic
    trigger_pin: GPIO14 #tx
    echo_pin: GPIO12    #echo/rx
    name: "Vijver Sensor"
    pulse_time: 10us
    accuracy_decimals: 2
    unit_of_measurement: cm
    update_interval: 30s
    timeout: 4.0m
    filters:
      - multiply: 100
      - median:
          window_size: 20
          send_every: 20
          send_first_at: 3    
