#waterput 
esphome:
  on_boot:
    - priority: -10
      then: 
        - lambda: |- 
            id(versie).publish_state("v25.5.2");
sensor:
  - platform: wifi_signal
    name: "waterput - WiFi Signal"
    update_interval: 120s
  - platform: ultrasonic
    trigger_pin: GPIO17    #echo/tx oranje
    echo_pin: GPIO16       #rx      geel
    name: "Vijver Sensor2"
    pulse_time: 10us
    accuracy_decimals: 2
    unit_of_measurement: cm
    update_interval: 10s
    timeout: 4.0m
    filters:
      - multiply: 100
      - median:
          window_size: 20
          send_every: 20
          send_first_at: 3
          
binary_sensor: 
  - platform: gpio
    pin:
      number: GPIO13 #rood D7
      mode: INPUT_PULLUP
    name: "Watersensor"
    device_class: door

text_sensor:
  - platform: template
    name: "waterput - versie"
    id: versie
    icon: 'mdi:alpha-v-circle-outline' 
    update_interval: 6h
  - platform: wifi_info
    ip_address:
      name: "waterput IP-adres"
      id: ip_adres
      icon: mdi:ip-network
    ssid:
      name: "waterput Netwerk"
      id: netwerk
      icon: mdi:access-point-network
    mac_address:
      name: "waterput Mac-adres"
      id: mac_adres
      icon: mdi:folder-key-network-outline

